import { CaptionCue, CaptionWord } from '../types';
import { SubtitleStyle } from '../../types';

/**
 * Converts a hex color (#RRGGBB or #RGB) into ASS &HAABBGGRR format.
 * ASS expects colors in BGR order with optional alpha (00 = fully opaque, FF = fully transparent).
 */
export function hexToAssColor(hex: string, alphaHex: string = '00'): string {
  if (!hex || typeof hex !== 'string') {
    return '&H00FFFFFF';
  }

  let clean = hex.replace('#', '').trim();
  if (clean.length === 3) {
    clean = clean.split('').map((c) => c + c).join('');
  }

  if (clean.length !== 6) {
    return '&H00FFFFFF';
  }

  const r = clean.slice(0, 2).toUpperCase();
  const g = clean.slice(2, 4).toUpperCase();
  const b = clean.slice(4, 6).toUpperCase();
  const a = alphaHex.toUpperCase().padStart(2, '0');

  return `&H${a}${b}${g}${r}`;
}

/**
 * Formats seconds into ASS timestamp format: H:MM:SS.cc (centiseconds)
 * @param seconds Floating point seconds
 */
export function formatAssTimestamp(seconds: number): string {
  if (typeof seconds !== 'number' || isNaN(seconds) || !isFinite(seconds) || seconds < 0) {
    throw new RangeError(`Invalid timestamp for ASS formatting: ${seconds}`);
  }

  const totalCentiseconds = Math.floor(Math.round(seconds * 1000) / 10);
  const cs = totalCentiseconds % 100;
  const totalSeconds = Math.floor(totalCentiseconds / 100);
  const secs = totalSeconds % 60;
  const totalMinutes = Math.floor(totalSeconds / 60);
  const minutes = totalMinutes % 60;
  const hours = Math.floor(totalMinutes / 60);

  const pad = (num: number, size: number) => String(num).padStart(size, '0');

  return `${hours}:${pad(minutes, 2)}:${pad(secs, 2)}.${pad(cs, 2)}`;
}

export interface AssSerializeOptions {
  style?: Partial<SubtitleStyle>;
  playResX?: number;
  playResY?: number;
  enableKaraoke?: boolean;
}

/**
 * Deterministically generates an Advanced SubStation Alpha (.ass) script from CaptionCues.
 * Independent of canvas rendering, deterministic, and supports word-level karaoke timing.
 */
export function generateAss(cues: CaptionCue[], options?: AssSerializeOptions): string {
  const {
    style: customStyle,
    playResX = 1080,
    playResY = 1920,
    enableKaraoke = true,
  } = options || {};

  // Default styling matching Clipper creator presets
  const fontFamily = customStyle?.fontFamily || 'Impact, sans-serif';
  const fontSize = customStyle?.fontSize || 56;
  const primaryColor = hexToAssColor(customStyle?.primaryColor || '#FFFFFF');
  const highlightColor = hexToAssColor(customStyle?.highlightColor || '#FACC15');
  const strokeColor = hexToAssColor(customStyle?.strokeColor || '#000000');
  const strokeWidth = customStyle?.strokeWidth !== undefined ? customStyle.strokeWidth : 3;
  const isUppercase = customStyle?.uppercase ?? true;
  const isKaraokeAnim = customStyle?.animation === 'karaoke' || enableKaraoke;

  // Numpad alignment: 2 = bottom center, 5 = middle center, 8 = top center
  let alignment = 2;
  let marginV = 220; // Safe area margin from bottom

  if (customStyle?.position === 'middle') {
    alignment = 5;
    marginV = 0;
  } else if (customStyle?.position === 'top') {
    alignment = 8;
    marginV = 240;
  }

  const header = `[Script Info]
; Script generated by Clipper Subtitle Engine
ScriptType: v4.00+
PlayResX: ${playResX}
PlayResY: ${playResY}
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${fontFamily},${fontSize},${primaryColor},${highlightColor},${strokeColor},&H80000000,-1,0,0,0,100,100,0,0,1,${strokeWidth},0,${alignment},40,40,${marginV},1
Style: Highlight,${fontFamily},${fontSize},${highlightColor},${primaryColor},${strokeColor},&H80000000,-1,0,0,0,100,100,0,0,1,${strokeWidth},0,${alignment},40,40,${marginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text`;

  if (!Array.isArray(cues)) {
    throw new Error('Cues must be an array');
  }

  if (cues.length === 0) {
    return header + '\n';
  }

  // Pre-validate all cues strictly before serializing
  for (let i = 0; i < cues.length; i++) {
    const cue = cues[i];
    if (!cue) {
      throw new Error(`Cue at index ${i} is missing or null`);
    }
    if (typeof cue.start !== 'number' || isNaN(cue.start) || !isFinite(cue.start) || cue.start < 0) {
      throw new RangeError(`Cue at index ${i} has invalid start timestamp: ${cue.start}`);
    }
    if (typeof cue.end !== 'number' || isNaN(cue.end) || !isFinite(cue.end) || cue.end <= cue.start) {
      throw new RangeError(`Cue at index ${i} has invalid end timestamp: ${cue.end} (start: ${cue.start})`);
    }
    if (typeof cue.text !== 'string' || cue.text.trim().length === 0) {
      throw new Error(`Cue at index ${i} has empty text`);
    }
  }

  const sorted = [...cues].sort((a, b) => a.start - b.start || a.sequence - b.sequence);
  const events: string[] = [];

  for (let i = 0; i < sorted.length; i++) {
    const cue = sorted[i];
    const startStr = formatAssTimestamp(cue.start);
    const endStr = formatAssTimestamp(cue.end);

    let textPayload = '';
    const hasWordTimings =
      Array.isArray(cue.words) &&
      cue.words.length > 0 &&
      cue.words.every(
        (w) =>
          typeof w.start === 'number' &&
          typeof w.end === 'number' &&
          !isNaN(w.start) &&
          !isNaN(w.end) &&
          w.end >= w.start
      );

    if (isKaraokeAnim && hasWordTimings) {
      // Build karaoke formatted string: {\k<centiseconds>}Word
      const parts: string[] = [];
      let cursor = cue.start;

      for (let wIdx = 0; wIdx < cue.words.length; wIdx++) {
        const w = cue.words[wIdx];
        const gapSeconds = w.start - cursor;

        if (gapSeconds > 0.02) {
          const gapCs = Math.round(gapSeconds * 100);
          if (gapCs > 0) {
            parts.push(`{\\k${gapCs}} `);
          }
        }

        const durSeconds = Math.max(0.01, w.end - w.start);
        const durCs = Math.max(1, Math.round(durSeconds * 100));
        let wordText = isUppercase ? w.word.toUpperCase() : w.word;

        // Apply word emphasis if present
        if (w.highlighted || w.emphasisStyle) {
          parts.push(`{\\c${highlightColor}\\k${durCs}}${wordText}{\\c${primaryColor}}`);
        } else {
          parts.push(`{\\k${durCs}}${wordText}`);
        }

        cursor = w.end;
      }

      textPayload = parts.join(' ');
    } else {
      // Degrade explicitly to normal dialogue timing without fake karaoke tags
      let cueText = isUppercase ? cue.text.toUpperCase() : cue.text;
      if (cue.emphasis) {
        textPayload = `{\\c${highlightColor}}${cueText}`;
      } else {
        textPayload = cueText;
      }
    }

    events.push(`Dialogue: 0,${startStr},${endStr},Default,,0,0,0,,${textPayload}`);
  }

  return `${header}\n${events.join('\n')}\n`;
}
